version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: datak-ag-alpine
        container_name: dag-panel
        restart: unless-stopped
        working_dir: /var/www/html
        tty: true
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:8080"
        networks:
            - datak-ag

    redis:
        image: redis:alpine
        container_name: dag-redis
        hostname: redis
        networks:
            - datak-ag
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
networks:
    datak-ag:

volumes:
    app:

