version: "3.8"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: datak-search
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
      TZ: Asia/Tehran
      node.name: es
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - datak-ag

  logstash:
    image: logstash:${ELASTIC_VERSION}
    container_name: logstash
    volumes:
      - ./.docker/elk/logstash/config/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - datak-ag
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - datak-ag
    restart: unless-stopped

networks:
    datak-ag:

volumes:
  elasticsearch_data:
    driver: local

