version: "3.8"

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        container_name: datak-search
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            ELASTIC_USERNAME: "elu"
            ELASTIC_PASSWORD: "elastic"
            TZ: Asia/Tehran

        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./.docker/elk/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
            - elasticsearch_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - datak-ag

    logstash:
      image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
      container_name: datak-logstash
      volumes:
        - ./.docker/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
        - ./.docker/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      ports:
        - 5044:5044
        - 50000:50000/tcp
        - 50000:50000/udp
        - 9600:9600
      environment:
        LS_JAVA_OPTS: -Xms256m -Xmx256m
        LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      networks:
        - datak-ag
      depends_on:
        - elasticsearch
      restart: unless-stopped

    kibana:
      image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
      container_name: datak-kibana
      volumes:
        - ./.docker/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      ports:
        - 5601:5601
      environment:
        KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      networks:
        - datak-ag
      depends_on:
        - elasticsearch
      restart: unless-stopped

networks:
    datak-ag:

volumes:
    elasticsearch_data:

